#!/usr/bin/env bash
#
# Get the domain name of an app.
# Useful when getting/setting user defaults with the `defaults` command.
#
# Usage: domain <app name>
# Example: `domain "Xcode"` returns `com.apple.dt.Xcode`
#

domain() {
	local app="/Applications/$1.app"

	if ! test -d "${app}"
	then
		echo "App not found: ${app}"
		return 1
	fi

	mdls -name kMDItemCFBundleIdentifier -raw "${app}"
}
